# loggerhelper-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggerhelper-api-deployment
  labels:
    app: loggerhelper-api
spec:
  replicas: 2 # Quante istanze (Pod) del container vuoi in esecuzione? Iniziamo con 2.
  selector:
    matchLabels:
      app: loggerhelper-api
  template:
    metadata:
      labels:
        app: loggerhelper-api
    spec:
      containers:
      - name: loggerhelper-api-container
        # Sostituisci "alexbypa/loggerhelper-api" con il tuo container su Docker Hub
        # oppure usa l'immagine locale se stai testando con Minikube/Docker Desktop
        image: alexbypa/loggerhelper-api:1.0.20
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # La porta interna esposta dal container (come nel Dockerfile)
        env: # <--- Questo blocco inietta le variabili d'ambiente
        - name: ASPNETCORE_URLS
          value: "http://+:8080" # <-- Forza l'ascolto su HTTP porta 8080
          
        # 1. Variabile per il Database Provider (richiesta da entrypoint.sh)
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Production"
          
        # 2. Risolve l'ERRORE CRITICO: DatabaseProvider
        - name: DatabaseProvider 
          value: "postgresql"
        
        # 3. Inietta la stringa di connessione per la chiave "ConnectionStrings:Default"
        #    (usa il Service name K8s di PostgreSQL: logger-db-postgresql)
        - name: ConnectionStrings__Default
          value: "Host=postgres-container;Port=5432;Database=test_db;Username=root;Password=root"

        - name: Serilog__SerilogConfiguration__LoggerTelemetryOptions__IsEnabled
          value: "0"

        - name: Serilog__SerilogConfiguration__LoggerTelemetryOptions__Provider
          value: "PostgreSQL"
          
        - name: Serilog__SerilogConfiguration__LoggerTelemetryOptions__ConnectionString
          value: "Host=postgres-container;Port=5432;Database=test_db;Username=root;Password=root"
          
        - name: Serilog__SerilogConfiguration__SerilogOption__MSSqlServer__connectionString
          value: "Server=mssql,1433;Database=test_db;User Id=SA;Password=strong!password#123;TrustServerCertificate=True"
          
        - name: Serilog__SerilogConfiguration__SerilogCondition__0__Level__0
          value: "Information"
          
        - name: Serilog__SerilogConfiguration__SerilogCondition__0__Level__1
          value: "Warning"
          
        - name: Serilog__SerilogConfiguration__SerilogCondition__0__Level__2
          value: "Error"
          
        - name: Serilog__SerilogConfiguration__SerilogCondition__0__Level__3
          value: "Fatal"
          
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" # Mezza CPU (500 millicore)
          requests:
            memory: "64Mi"
            cpu: "250m"