apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: webapi
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_USER } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_PASSWORD } }
        - name: POSTGRES_DB
          valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_DB } }
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          tcpSocket: { port: 5432 }
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: webapi
spec:
  selector: { app: postgres }
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
