apiVersion: v1
kind: Service
metadata:
  name: postgres-container
  namespace: webapi
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP